In [2]:
import torch 
import numpy as np
import torch.nn as nn

torch.manual_seed(42)

# 1. Kham pha tensor

## 1.1 Tao tensor

In [3]:
# tensor from list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(type(x_data))

# tensor from numpy
data = np.array(data)
x_data = torch.from_numpy(data)
print(x_data)

# tensor from random values
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n {x_rand}\n")

# shape, dtype, device from tensor
print(f"Shape of tensor: {x_rand.shape}")
print(f"DataType of tensor: {x_rand.dtype}")
print(f"Device of tensor: {x_rand.device}")

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])
Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

Shape of tensor: torch.Size([2, 2])
DataType of tensor: torch.float32
Device of tensor: cpu


## 1.2 Cac phep toan voi tensor

In [4]:
print(f"X data: \n {x_data}\n")

x_total = x_data + x_data
print(f"X total: \n {x_total}\n")

x_mul = x_data * 5
print(f"X mul: \n {x_mul}\n")

x_matmul = x_data @ x_data.T
print(f"X matmul: \n {x_matmul}\n")

X data: 
 tensor([[1, 2],
        [3, 4]])

X total: 
 tensor([[2, 4],
        [6, 8]])

X mul: 
 tensor([[ 5, 10],
        [15, 20]])

X matmul: 
 tensor([[ 5, 11],
        [11, 25]])



## 1.3 Indexing and Slicing

In [5]:
print(f"X_data \n{x_data}\n")
print(f"First row: \n {x_data[0]}\n")
print(f"Second column: \n {x_data[:, 1]}\n")
print(f"X_data[1,1]: \n {x_data[1,1]}\n")


X_data 
tensor([[1, 2],
        [3, 4]])

First row: 
 tensor([1, 2])

Second column: 
 tensor([2, 4])

X_data[1,1]: 
 4



## 1.4 Thay doi hinh dang tensor

In [6]:
x_data = torch.rand(4, 4)
print(f"X data: \n {x_data}\n X.shape: {x_data.shape}\n")

x_view = x_data.view(16, 1)
print(f"X reshape: \n {x_view}\n X.shape: {x_view.shape}\n")

x_reshape = x_data.reshape(16, 1)
print(f"X reshape: \n {x_reshape}\n X.shape: {x_reshape.shape}\n")


X data: 
 tensor([[0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274]])
 X.shape: torch.Size([4, 4])

X reshape: 
 tensor([[0.3904],
        [0.6009],
        [0.2566],
        [0.7936],
        [0.9408],
        [0.1332],
        [0.9346],
        [0.5936],
        [0.8694],
        [0.5677],
        [0.7411],
        [0.4294],
        [0.8854],
        [0.5739],
        [0.2666],
        [0.6274]])
 X.shape: torch.Size([16, 1])

X reshape: 
 tensor([[0.3904],
        [0.6009],
        [0.2566],
        [0.7936],
        [0.9408],
        [0.1332],
        [0.9346],
        [0.5936],
        [0.8694],
        [0.5677],
        [0.7411],
        [0.4294],
        [0.8854],
        [0.5739],
        [0.2666],
        [0.6274]])
 X.shape: torch.Size([16, 1])



# 2. Tu dong tinh dao ham voi autograd

In [7]:
x = torch.ones(1, requires_grad=True)
print("x:", x)

y = x + 2
print("y:", y)
print(f"grad_fn của y: {y.grad_fn}")

z = y * y * 3
print("z:", z)
z.backward(retain_graph=True) # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

z.backward()
print(f"Đạo hàm của z theo x lần 2: {x.grad}")  # cộng dồn giá trị: 18 + 18 = 36


x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x000001AF86969210>
z: tensor([27.], grad_fn=<MulBackward0>)
Đạo hàm của z theo x: tensor([18.])
Đạo hàm của z theo x lần 2: tensor([36.])


# 3. Xây dựng model với nn.Module

# 3.1 nn.Linear

In [8]:
linear_layer = nn.Linear(in_features=5, out_features=2)
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều
print("Input tensor \n", input_tensor)
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print("Output:", output)

Input tensor 
 tensor([[ 1.3221,  0.8172, -0.7658, -0.7506,  1.3525],
        [ 0.6863, -0.3278,  0.7950,  0.2815,  0.0562],
        [ 0.5227, -0.2384, -0.0499,  0.5263, -0.0085]])
Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output: tensor([[-0.4725, -1.1789],
        [ 0.1990, -0.7067],
        [ 0.4769, -0.4182]], grad_fn=<AddmmBackward0>)


## 3.2 nn.Embedding

In [9]:
embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=3)
print("Embedding layer:\n", embedding_layer.weight)
input_indices = torch.tensor([1, 5, 0, 8])
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Embedding layer:
 Parameter containing:
tensor([[ 1.4451,  0.8564,  2.2181],
        [ 0.5232,  0.3466, -0.1973],
        [-1.0546,  1.2780, -0.1722],
        [ 0.5238,  0.0566,  0.4263],
        [ 0.5750, -0.6417, -0.4976],
        [ 0.4747, -2.5095,  0.4880],
        [ 0.7846,  0.0286,  0.6408],
        [ 0.5832,  0.2191,  0.5526],
        [-0.1853,  0.7528,  0.4048],
        [ 0.1785,  0.2649,  1.2732]], requires_grad=True)
Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.5232,  0.3466, -0.1973],
        [ 0.4747, -2.5095,  0.4880],
        [ 1.4451,  0.8564,  2.2181],
        [-0.1853,  0.7528,  0.4048]], grad_fn=<EmbeddingBackward0>)


## 3.3 nn.Module

In [11]:
class MyModel(nn.Module):
    def __init__(self, vocab_size: int, embedding_dim: int, hidden_dim: int, output_dim: int):
        super().__init__()
        self.ln = nn.Linear(in_features=embedding_dim, out_features=hidden_dim)
        self.emb = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)
        self.activation = nn.ReLU()
        self.out = nn.Linear(in_features=hidden_dim, out_features=output_dim)
        
    def forward(self, x):
        x = self.emb(x)
        x = self.ln(x)
        x = self.activation(x)
        x = self.out(x)
        return x
    
def test():
    model = MyModel(vocab_size=10, embedding_dim=3, hidden_dim=4, output_dim=2)
    x = torch.tensor([1, 5, 0, 8])
    output = model(x)
    print("Input tensor \n", x)
    print(f"Input shape: {x.shape}")
    print(f"Output shape: {output.shape}")
    print(f"Output: {output}")
    
test()

Input tensor 
 tensor([1, 5, 0, 8])
Input shape: torch.Size([4])
Output shape: torch.Size([4, 2])
Output: tensor([[-0.0332,  0.4619],
        [ 0.0808,  0.3076],
        [ 0.1161,  0.2583],
        [ 0.1682,  0.1902]], grad_fn=<AddmmBackward0>)
